apiVersion: v1

kind: Pod

meatadata: 
  name: postgres-pod
  labels:
    name: postgres-pod
    app:  demo-postgres-app

spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432