apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: result-service
    app: demo-result-app

spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: result-app-pod
    app:  demo-result-app